PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX hisco: <https://iisg.amsterdam/hisco/>
PREFIX hisco-cat: <https://iisg.amsterdam/hisco/code/hisco/>

PREFIX local_fuseki: <http://svprre02:8080/fuseki/tdb/sparql>
PREFIX lassyklein: <http://localhost:8080/sparql2xquery/sparql2xquery>


PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX ud: <http://universaldependencies.org/u/dep/>
PREFIX : <http://example.org/>

PREFIX molex:  <http://rdf.ivdnt.org/lexica/molex/v1.0/>
PREFIX wn: <http://wordnet-rdf.princeton.edu/ontology#>

PREFIX diamant:      <http://rdf.ivdnt.org/schema/diamant#>

SELECT distinct  ?adj ?noun ?pn ?p ?eform
WHERE {
  SERVICE lassyklein:
  {
     ?somenounnode ud:nmod ?someadjnode .
     ?somenounnode :text ?noun .
     ?someadjnode :text ?adj .
     ?someadjnode ud:inflection ?b .
     values ?b {"zonder"}
  } .
  graph molex:
  {
    ?ae ontolex:canonicalForm ?acf .
    ?acf ontolex:writtenRep ?adj .
    ?ae ontolex:lexicalForm ?alf .
    ?alf wn:part_of_speech ?p .
    FILTER regex(?p, ".*degree=pos.*infl=e.*") .
    ?alf ontolex:writtenRep ?eform .
    ?ne ontolex:lexicalForm ?nlf .
    ?nlf ontolex:writtenRep ?noun .
    ?ne wn:part_of_speech ?pn .
    FILTER regex(?pn, ".*gender=[mf].*") .
  }
} limit 1000
