PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX hisco: <https://iisg.amsterdam/hisco/>
PREFIX hisco-cat: <https://iisg.amsterdam/hisco/code/hisco/>

PREFIX local_fuseki: <http://svprre02:8080/fuseki/tdb/sparql>
PREFIX lassyklein: <http://localhost:8080/sparql2xquery/sparql2xquery>


PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX ud: <http://universaldependencies.org/u/dep/>
PREFIX : <http://example.org/>

PREFIX diamant:      <http://rdf.ivdnt.org/schema/diamant#>

SELECT distinct ?pw ?ow ?lvw ?lvl
WHERE {
  SERVICE lassyklein:
  {
      ?pred ud:nsubj ?onderwerp .
      ?pred ud:obj ?lv .
      ?onderwerp :word ?ow .
      ?pred :word ?pw . 
      ?lv :word ?lvw
  } .
  graph <http://rdf.ivdnt.org/lexica/dbnl_similarity/>
  {
    ?sim diamant:source "woede" . ?sim diamant:target ?lvl
  } .
  graph <http://rdf.ivdnt.org/lexica/diamant/v1.0/>
  {
    ?e ontolex:canonicalForm ?lvc  . 
    ?lvc ontolex:writtenRep ?lvl .
    ?e ontolex:lexicalForm ?lvf .
    ?lvf ontolex:writtenRep ?lvw
  }
}
