name: Run links.py on commit of linked.md

on:
  push:
    paths:
      - "src/main/scala/corpusprocessing/GCND/dialectconstructions.md"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install any required dependencies (if any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies if you have a requirements.txt (optional)
        # pip install -r requirements.txt

    # Run the Python script to process the file
    - name: Run links.py
      run: |
        python3 src/main/scala/corpusprocessing/GCND/links.py src/main/scala/corpusprocessing/GCND/dialectconstructions.md > src/main/scala/corpusprocessing/GCND/dialectconstructions_linked.md

    # Commit and push changes if the script generates a new file
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/main/scala/corpusprocessing/GCND/dialectconstructions_linked.md
        git commit -m "Auto-update dialectconstructions_linked.md"
        git push
      # Only run this step if there are changes to commit
      if: success() && steps.files.outputs.changed == 'true'

